### ISSUE TITLE
Laptop keyboards?

### ISSUE THREAD

**Issue by hewitt** [tadosappo/nasskan#5]
Is this restricted to USB keyboards only? I can't find any ID_VENDOR_ID or ID_MODEL_ID associated with a Dell XPS laptop running Ubuntu 19.10.

**Comment by tadosappo** [comment]
I'm using nasskan with my laptop keyboard. My XPS13 keyboard is named AT Translated 2 Keyboard FYI. You have to find some properties specific to that keyboard. I think using MAJOR and MINOR is good https://github.com/tadosappo/nasskan/blob/master/examples/my-personal-config.yaml#L560

**Comment by hewitt** [comment]
Ah, I see. Thank you!

**Comment by chapmanjacobd** [comment]
This is how I solved it for me:

```
udevadm info --export-db|less -FSRXc
```

press `/` to search for keyb. you will see something like:

```
E: NAME="AT Translated Set 2 keyboard"
E: PHYS="isa0060/serio0/input0"
E: PROP=0
E: EV=120013
E: KEY=402000000 3803078f800d001 feffffdfffefffff fffffffffffffffe
E: MSC=10
E: LED=7
E: MODALIAS=input:b0011v0001p0001eAB41-e0,1,4,11,14,k71,72,73,74,75,76,77,79,7A,7B,7C,7D,7E,7F,80,8C,8E,8F,9B,9C,9D,9E,9F,A3,A4,A5,A6,AC,AD,B7,B8,B9,D9,E2,ram4,l0,1,2,sfw
E: USEC_INITIALIZED=38558106
E: ID_INPUT=1
E: ID_INPUT_KEY=1
E: ID_INPUT_KEYBOARD=1
E: ID_BUS=i8042
E: ID_SERIAL=noserial
E: ID_PATH=platform-i8042-serio-0
E: ID_PATH_TAG=platform-i8042-serio-0
E: ID_FOR_SEAT=input-platform-i8042-serio-0
E: TAGS=:seat:
```

I used this:

```yaml
version: 1
devices:
  - if:
      ID_BUS: i8042
      ID_INPUT_KEYBOARD: 1
```
